stages:
  - deploy

deploy-prod:
  stage: deploy
  
  only:
    - master
  tags:
    - publish-srv
  image: docker:latest
  services:
    - docker:dind
  environment: "production"
  script:
    - docker run --rm -v $(pwd):/source -v /web/speedverse.io:/target alpine cp -r /source/* /target
